In [1]:
import pyuvsim
import pyuvdata
import pyradiosky
import astropy
import numpy as np
import importlib
importlib.reload(pyuvsim)

<module 'pyuvsim' from '/opt/devel/rbyrne/envs/py310/lib/python3.10/site-packages/pyuvsim/__init__.py'>

In [2]:
uv = pyuvdata.UVData()
uv.read("/lustre/rbyrne/2025-06-13/20250613_070132_55MHz.ms")
uv.phase_to_time(np.mean(uv.time_array))

Setting telescope_location to value in known_telescopes for OVRO-LWA.
The uvw_array does not match the expected values given the antenna positions. The largest discrepancy is 12.14008682625115 meters. This is a fairly common situation but might indicate an error in the antenna positions, the uvws or the phasing.


In [3]:
np.shape(uv.nsample_array)

(62128, 192, 4)

In [4]:
uv.spw_array

array([0])

In [5]:
uv.__dict__

{'_Ntimes': <pyuvdata.parameter.UVParameter at 0x7f64a5f266b0>,
 '_Nbls': <pyuvdata.parameter.UVParameter at 0x7f64d69b7580>,
 '_Nblts': <pyuvdata.parameter.UVParameter at 0x7f64a5f82fe0>,
 '_Nfreqs': <pyuvdata.parameter.UVParameter at 0x7f64a5f83070>,
 '_Npols': <pyuvdata.parameter.UVParameter at 0x7f64a5f839d0>,
 '_data_array': <pyuvdata.parameter.UVParameter at 0x7f64a5f83e20>,
 '_vis_units': <pyuvdata.parameter.UVParameter at 0x7f64a5f25cf0>,
 '_nsample_array': <pyuvdata.parameter.UVParameter at 0x7f64a5f83e50>,
 '_flag_array': <pyuvdata.parameter.UVParameter at 0x7f64a5f830a0>,
 '_Nspws': <pyuvdata.parameter.UVParameter at 0x7f64a5f83a00>,
 '_spw_array': <pyuvdata.parameter.UVParameter at 0x7f64a5f83af0>,
 '_uvw_array': <pyuvdata.parameter.UVParameter at 0x7f64a5f83040>,
 '_time_array': <pyuvdata.parameter.UVParameter at 0x7f64a5956e60>,
 '_lst_array': <pyuvdata.parameter.UVParameter at 0x7f64a5957400>,
 '_ant_1_array': <pyuvdata.parameter.UVParameter at 0x7f64a5957460>,
 '_ant_2_

In [ ]:
#uv.select(bls=(0, 1, "xx"))
freq_hz = 50e6
channel_width = 2e3
##total_time_interval_s = 10
##total_freq_interval_hz = 200e3
total_time_interval_s = 1
total_freq_interval_hz = 4e3
integration_time = 0.1
time_array_s = np.arange(-total_time_interval_s/2, total_time_interval_s/2, integration_time)
uv.freq_array = np.arange(freq_hz-total_freq_interval_hz/2, freq_hz+total_freq_interval_hz/2, channel_width)
uv.Nfreqs = len(uv.freq_array)
uv.time_array = np.mean(uv.time_array) + time_array_s/86400
uv.Ntimes = len(time_array_s)
uv.Nbls = 1
uv.Nblts = uv.Ntimes
uv.Npols = 1
uv.Nants_data = 2
uv.Nspws = 1
uv.flex_spw_id_array = np.full(uv.Nfreqs, np.mean(uv.spw_array), dtype=int)
uv.ant_1_array = np.zeros(uv.Nblts, dtype=int)
uv.ant_2_array = np.ones(uv.Nblts, dtype=int)
uv.channel_width = np.full(uv.Nfreqs, channel_width)
uv.integration_time = np.full(uv.Nblts, integration_time)
uv.baseline_array = np.full(uv.Nblts, 2048 + 2**16)
uv.data_array = np.zeros((uv.Nblts, uv.Nfreqs, uv.Npols), dtype=complex)
uv.flag_array = np.zeros((uv.Nblts, uv.Nfreqs, uv.Npols), dtype=bool)
uv.nsample_array = np.ones((uv.Nblts, uv.Nfreqs, uv.Npols), dtype=float)
uv.polarization_array = np.array([-5])
uv.uvw_array = np.zeros((uv.Nblts, 3), dtype=float)
uv.uvw_array[:, 0] = 3e3
uv.set_lsts_from_time_array()
uv.phase_center_app_ra = uv.phase_center_app_ra[:uv.Nblts]
uv.phase_center_app_dec = uv.phase_center_app_dec[:uv.Nblts]
uv.phase_center_frame_pa = uv.phase_center_frame_pa[:uv.Nblts]
uv.phase_center_id_array = uv.phase_center_id_array[:uv.Nblts]
uv.scan_number_array = None
uv.phase_to_time(np.mean(uv.time_array))


The uvw_array does not match the expected values given the antenna positions. The largest discrepancy is 2963.75690856336 meters. This is a fairly common situation but might indicate an error in the antenna positions, the uvws or the phasing.
The entry name zenith_at_jd2460839.792738 is not unique inside the phase center catalog, adding anyways.
The provided name zenith_at_jd2460839.792738 is already used but has different parameters. Adding another entry with the same name but a different ID and parameters.


In [7]:
uv.uvw_array

array([[3.62665576e+01, 6.26319074e+02, 5.12094937e-01],
       [3.62637962e+01, 6.26319234e+02, 5.11894522e-01],
       [3.62610359e+01, 6.26319394e+02, 5.11694203e-01],
       [3.62582744e+01, 6.26319554e+02, 5.11493820e-01],
       [3.62555141e+01, 6.26319714e+02, 5.11293534e-01],
       [3.62527527e+01, 6.26319874e+02, 5.11093183e-01],
       [3.62499913e+01, 6.26320034e+02, 5.10892849e-01],
       [3.62472310e+01, 6.26320193e+02, 5.10692611e-01],
       [3.62444695e+01, 6.26320353e+02, 5.10492308e-01],
       [3.62417092e+01, 6.26320513e+02, 5.10292102e-01]])

In [8]:
beam = pyuvdata.UVBeam()
beam.read("/lustre/rbyrne/LWA_10to100_MROsoil_efields.fits")
beam.select(feeds="e")
beam.peak_normalize()
beam_list = pyuvsim.BeamList(beam_list=[beam])

In [9]:
np.max(np.abs(beam.data_array))

1.0000000000000002

In [10]:
zenith_loc = astropy.coordinates.SkyCoord([astropy.coordinates.ICRS(ra=np.mean(uv.lst_array)*astropy.units.rad, dec=uv.telescope.location.lat)])

In [11]:
type(zenith_loc)

astropy.coordinates.sky_coordinate.SkyCoord

In [12]:
cat = pyradiosky.SkyModel()
cat.Ncomponents = 1
cat.Nfreqs = 1
cat.component_type = "point"
cat.name = np.array(["source1"])
cat.skycoord = zenith_loc
cat.spectral_type = "spectral_index"
cat.spectral_index = np.zeros(cat.Ncomponents)
cat.reference_frequency = np.array([np.mean(uv.freq_array)])*astropy.units.Hz
cat.stokes = np.zeros((4, 1, 1))
cat.stokes[0, 0, 0] = 1
cat.stokes *= astropy.units.Jy
cat.history = ""
cat._n_polarized = 0
cat.check()

True

In [13]:
catalog_formatted = pyuvsim.simsetup.SkyModelData(cat)

In [14]:
#catalog_formatted.spectral_type = "spectral_index"
#catalog_formatted.spectral_index = np.zeros(cat.Ncomponents)
#catalog_formatted.reference_frequency = np.mean(uv.freq_array)#*astropy.units.Hz

In [15]:
output_uv = pyuvsim.uvsim.run_uvdata_uvsim(
    input_uv=uv,
    beam_list=beam_list,
    beam_dict=None,  # Same beam for all ants
    catalog=cat,
    quiet=False,
)

Nbls: 1
Ntimes: 10
Nfreqs: 2
Nsrcs: 1
Tasks:  20.0
5.00% completed. 0:00:01.119754  elapsed. 0:00:21.275318 remaining. 

10.00% completed. 0:00:02.204597  elapsed. 0:00:19.841371 remaining. 

15.00% completed. 0:00:02.206859  elapsed. 0:00:12.505536 remaining. 

20.00% completed. 0:00:03.265757  elapsed. 0:00:13.063026 remaining. 

25.00% completed. 0:00:03.268138  elapsed. 0:00:09.804413 remaining. 

30.00% completed. 0:00:04.268563  elapsed. 0:00:09.959980 remaining. 

35.00% completed. 0:00:04.270396  elapsed. 0:00:07.930736 remaining. 

40.00% completed. 0:00:05.309501  elapsed. 0:00:07.964251 remaining. 

45.00% completed. 0:00:05.311450  elapsed. 0:00:06.491773 remaining. 

50.00% completed. 0:00:06.332217  elapsed. 0:00:06.332217 remaining. 

55.00% completed. 0:00:06.334606  elapsed. 0:00:05.182859 remaining. 

60.00% completed. 0:00:07.360992  elapsed. 0:00:04.907328 remaining. 

65.00% completed. 0:00:07.362862  elapsed. 0:00:03.964618 remaining. 

70.00% completed. 0:00:08.4

The parameter `blt_order` could not be identified for input_uv  so the ordering cannot be restored.The output UVData object will have (time, baseline) ordering.
Recalculating uvw_array without adjusting visibility phases -- this can introduce significant errors if used incorrectly.


In [16]:
output_uv.data_array

array([[[0.49920261+0.02814769j],
        [0.49920255+0.02814881j]],

       [[0.49920879+0.02803808j],
        [0.49920873+0.0280392j ]],

       [[0.49921495+0.02792853j],
        [0.49921488+0.02792965j]],

       [[0.49922108+0.02781895j],
        [0.49922102+0.02782006j]],

       [[0.49922719+0.02770941j],
        [0.49922712+0.02771052j]],

       [[0.49923327+0.02759984j],
        [0.49923321+0.02760094j]],

       [[0.49923933+0.02749027j],
        [0.49923927+0.02749137j]],

       [[0.49924536+0.02738076j],
        [0.4992453 +0.02738185j]],

       [[0.49925137+0.02727121j],
        [0.49925131+0.0272723j ]],

       [[0.49925735+0.02716171j],
        [0.4992573 +0.02716279j]]])